version: '3' # docker-compose version
services: # services which our app going to use. (list of containers we want to create)
  mongo: # container name 
    image: mongo # On which image container will build
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

    
  api-server:
    image: api-server
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes: # enable persistence of database data across container restart
  mongo-data:
    driver: local